apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voice-dictation
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tmforge
spec:
  project: default
  source:
    repoURL: https://github.com/tykrysTM/voice-dictation.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: voice-dictation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
